<?php
	$v_params 	= $this->getParams();
	$o_produto  = $v_params['o_produto']; 
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    	
    	<script type="text/javascript">
		
		function id( el )
		{
			return document.getElementById( el );
		}
		
		function getMoney( el )
		{
			var money = id( el ).value.replace( ',', '.' );
			return parseFloat( money );
		}

		function formatReal(num) 
		{
    		var p = num.toFixed(2).split(".");
    		return "R$ " + p[0].split("").reverse().reduce(function(acc, num, i, orig) {
        	return  num + (i && !(i % 3) ? "." : "") + acc;
    		}, "") + "," + p[1];
		}

		function soma()
		{	
			var total     = 0;
			var precounit = <?php echo $o_produto->getPreco(); ?>;
			<?php //grades
    			foreach( $o_produto->getGrades() AS $o_grade )
				{
				   if( $o_grade->getQtdProd() > 0 )
				   { 	 
					
			?>
			total = total + getMoney( 'campo<?php echo $o_grade->getId(); ?>' ) * precounit;
			
			<?php
				   }
				}
			?>	
			id('total').value = formatReal( total );
		}
	</script>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
     <!-- Menus -->
    	<?php
    		if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
			{	
    	 ?>
    	 <!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li class="active"><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=cliente&action=list">Clientes</a></li>
              				<li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
    	
    	 <?php 
			}
			else
    	 	{	
    	 ?>
    	 <!-- Menu Cliente-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Meu Carrinho </a> </li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li  class="active"><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=cliente&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=pedido&action=list">Meus Pedidos</a></li>
              				<li> <a href="?ctrl=titulo&action=list">Meus Títulos</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
   	 	<?php
   	 		}
   	 	?> 
   	 	<!-- Fim Menus-->
 		<div class="container">
    		<div class="row-fluid">
				<div class="span">
          			<h1 style="text-align: center; font-size: 25px; line-height: 16px; padding: 10px 0 2px" >
    				   <?php echo $o_produto->getDescricao() .' - '.$o_produto->getReferencia()  ?>
    				</h1>
    				<hr>
    				<p class="muted" style="color: #C8002A; text-align: center;  font-weight:bold; font-size: 20px" ><?php echo 'Preço por peça: R$ '.number_format($o_produto->getPreco(), 2, ',', '.'); ?></p>
    			 	<hr>
    			 	
    			 	<!-- Grade -->
    			 	<form method="post" class="form">
    			 	<table class="table table-bordered">
    			 		<thead>
    			 			<tr>
								<th>Grade</th>
								<th>Estoque</th>
								<th>Comprar</th>
							</tr>
						</thead>
						<tbody>
    						<?php //grades
    						 	$total = 0;
    							foreach( $o_produto->getGrades() AS $o_grade )
								{
									 	
							?>
									<tr <?php if( $o_grade->getQtdProd() <= 0 ) { ?> class="warning" <?php } ?> >
										<td><?php echo $o_grade->getGrade() ?></td>
										<td><?php echo $o_grade->getQtdProd() ?></td>
										<td>
											<?php 
												  if( $o_grade->getQtdProd() > 0 ) 
												  {
										    ?>
											<select class="span3" name="campo<?php echo $o_grade->getId(); ?>" id="campo<?php echo $o_grade->getId(); ?>" onchange="soma();" >
								 				<?php 
								 					for ($i = 0; $i <= $o_grade->getQtdProd(); $i++) 
								 					{
  							  					?>
  							  					<?php 
								 						$id_user = intval ( $_SESSION['_app_user']['id'] );
														if( isset( $_SESSION['_app_cart_'.$id_user ] [$o_produto->getId()] ) )
														{
													   		if( isset( $_SESSION['_app_cart_'.$id_user ] [$o_produto->getId()] [$o_grade->getId()]) )
													   		{
													   	  		$int_qtd_sel_ = $_SESSION['_app_cart_'.$id_user ] [$o_produto->getId()] [$o_grade->getId()]; 
													   		}
													   		else 
													   		{
													      		$int_qtd_sel_ = 0;		
													   		}	
														}
														else
														{
															$int_qtd_sel_ = 1;
														} 
								 				
								 				?>
								 				<option <?php if( $int_qtd_sel_ == $i ){ ?> selected="" <?php } ?>> <?php echo $i ?></option>
								 				
								 				
								 				<?php
													}
								 				?>
											</select>
											<?php 
												$total = $total  + $int_qtd_sel_ * $o_produto->getPreco();  
												}
											?>
										</td>
									</tr>
    						<?php
								}
    							// fim grades 
    						?>
						</tbody>
    				</table>
    				<!-- Fim - Grades -->
    			 	
    			 	
    				<div class="row-fluid">
    				<p class="muted" style="color: #111111; text-align: right;  font-weight:bold; font-size: 20px" > 
    					Total: <input class="span2" name="total" readonly="readonly" id="total" value="<?php echo 'R$ '.number_format($total, 2, ',', '.');  ?>"/>
    				</p>
    				</div>
    				</br>
 					<div class="row-fluid">
    					<div class="span5 offset1">
    						<a href="?ctrl=index" class="btn btn-block btn-large">voltar</a>
    					</div>
    					<div class="span5">
    						<input name="Submit" value="continuar" class="btn btn-block btn-large btn-success" type="submit">
    					</div>
   					</div>
   					
   					</form>
   				</div> <!--/span-->  
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>

   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
  	</body>
</html>

