<?php
 	$v_params 	 	  = $this->getParams();
	$v_mensagens      = $v_params['v_mensagens']; 
	$qtd_mensagens 	  = $v_params['qtd_mensagens'];
	$dat_dataini      = $v_params['dat_dataini'];
	$dat_datafim      = $v_params['dat_datafim'];
	$int_pagina	   	  = $v_params['int_pagina']; 
	$int_numporpagina = $v_params['int_numporpagina'];
	$int_totalreg 	  = $v_params['int_totalreg'];
	$boo_nao_lidas    = $v_params['boo_nao_lidas']; 		
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
		<link href="view/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
		<link href="view/css/bootstrap-combined.min.css" rel="stylesheet">
	 
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
    	 <!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=cliente&action=edit">Clientes</a></li>
              				<li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li class="active" ><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
 		<div class="container">
    		<div class="row-fluid">
    			<div class="span">
    				<form method="post" >
					<div class="well well-small" style="text-align: center;">
 						
 						
						<div id="" class="input-append">
							<label style="padding-top:08px">
 								Data final de 
 							</label>
 						</div>
 						&nbsp
 						<div id="dataini" class="input-append date">
      						<input value="<?php echo $dat_dataini; ?>" type="text" class="input-small" name="dataini"></input>
     			 			 <span class="add-on">
        					 	<i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      						</span>
    					</div>
    					<div id="" class="input-append">
							<label style="padding-top:08px">
    							&nbsp até &nbsp
    						</label>
    					</div>
    					<div id="datafim" class="input-append date">
      						<input value="<?php echo $dat_datafim; ?>" type="text" class="input-small" name="datafim" ></input>
     			 			 <span class="add-on">
        					 	<i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      						</span>
    					</div>
    					&nbsp
    					<div id="" class="input-append">
    					 	<label class="checkbox" style="padding-top:08px">
								<input type="checkbox" name="nlidas" id="nlidas"  <?php  if( $boo_nao_lidas == true ) { ?> checked="" <?php } ?> > Somente não lidas   
							</label>
						</div>
    					&nbsp
    					<div id="" class="input-append">
    						<button type="submit" class="btn"> filtrar </button>
    					</div>
					</div>
					</form>
					      				
          			<!-- Sem Mensagens -->
          			<?php 
          				if( $qtd_mensagens == 0 )
          				{  	
          			?>
          			<div class="row-fluid">
						<div class="alert alert-info">
          				<h4>
          					<stron>Sem Mensagens!</stron>
          				</h4>
          				<p>
          					Nenhum mensagem foi localizada com os filtros utilizados!
          				</p>
          			</div>
      				</div><!--/row-->	
          			<!-- Sem Mensagens -->
          			<?php
						}
						else
						{ 
          			?> 
          			<!-- Menagens -->
          			<table class="table table-bordered">
    			 		<thead>
    			 			<tr>
								<th>Data Inicial</th>
								<th>Data Final  </th>
								<th>Mensagem    </th>
								<th>Marcar Como</th>
							</tr>
						</thead>
						<tbody>
    						<?php
    							foreach( $v_mensagens AS $o_mensagem )
								{	
									if ( $o_mensagem->getConfLeitura() == 'f' )
									{
										$boo_lida = 'true'; 
									}
									else
									{
										$boo_lida = 'false';
									}		  
							?>
									<tr>
    									<td style="width: 10%"> <?php  echo strftime("%d/%m/%Y", strtotime($o_mensagem->getDataIni())); ?></td>
    									<td style="width: 10%"> <?php  echo strftime("%d/%m/%Y", strtotime($o_mensagem->getDataFim())); ?></td>
    									<td style="width: 70%"> <?php  echo $o_mensagem->getMensagem() ?></td>
    									<td style="width: 10%">
    										<a href="?ctrl=mensagem&action=read&id_men=<?php echo $o_mensagem->getId().'&b_l='.$boo_lida; ?>" class="btn-block btn <?php if( $boo_lida == 'true' ) { echo 'btn-success'; } else { echo 'btn-danger'; } ?>">
    											<?php if( $boo_lida == 'true' ) { echo 'lida'; } else { echo 'não lida'; } ?>
    										</a>
    									</td>
    								</tr>
    						<?php
								}
							?>  						
						</tbody>
    				</table>
    				
    				<!-- Paginação -->
    			    <ul class="pager">
    			    <?php
    			    	$int_prox   = $int_pagina + 1;
						$int_ant    = $int_pagina - 1;		
						$int_ultima = @ceil( $int_totalreg / $int_numporpagina );
					
    			       if ( $int_ant >= 0 )
					   {
					 ?>
					 	<li class="previous">
					 	<a href="?ctrl=mensagem&action=list&in_pg=<?php echo $int_ant.'&dt_i='.$dat_dataini.'&dt_f='.$dat_datafim.'&n_li='.$boo_nao_lidas; ?>">&larr; Mensagens anteriores</a>
					 <?php
					   }
					   else
					   {
					 ?> 
						<li class="previous disabled">
						<a href="">&larr; Mensagens anteriores</a>	
					 <?php
					   }
					 ?>		
    					</li>
    				
    				<?php					
    			       if ( $int_prox < $int_ultima )
					   {
					 ?>
					 	<li class="next">
					 	<a href="?ctrl=mensagem&action=list&in_pg=<?php echo $int_prox.'&dt_i='.$dat_dataini.'&dt_f='.$dat_datafim.'&n_li='.$boo_nao_lidas; ?>">Mais mensagens &rarr;</a>
					 <?php
					   }
					   else
					   {
					 ?> 
						<li class="next disabled">
						<a href="">Mais mensagens &rarr;</a>	
					 <?php
					   }
					 ?>		
    					</li>
    				</ul>
    				<!-- Fim paginação -->
    			<?php	
    			 }  // Fim com Itens
    			?>	
       			</div> <!--Span-->
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>

   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
		<script src="view/js/bootstrap-datetimepicker.min.js"></script>	
		<script src="view/js/bootstrap-datetimepicker.pt-BR.js"></script>
    	<script type="text/javascript">
      		$('#dataini').datetimepicker({
        		format: 'dd/MM/yyyy',
        		language: 'pt-BR',
        		pickTime: false
      		});
      		$('#datafim').datetimepicker({
        		format: 'dd/MM/yyyy',
        		language: 'pt-BR',
        		pickTime: false
      		});
    	</script>	
  	</body>
</html>