<?php
 	$v_params 	= $this->getParams();
	$v_carrinho = $v_params['v_carrinho']; 
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
    	<!-- Menus -->
    	<?php
    		if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
			{	
    	 ?>
    	 <!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li  class="active" > <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=cliente&action=list">Clientes</a></li>
              				<li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
    	
    	 <?php 
			}
			else
    	 	{	
    	 ?>
    	 <!-- Menu Cliente-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li class="active"> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Meu Carrinho </a> </li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=cliente&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=pedido&action=list">Meus Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Meus Títulos</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
   	 	<?php
   	 		}
   	 	?> 
   	 	<!-- Fim Menus-->
 		<div class="container">
    		<div class="row-fluid">
    			<div class="span">
          			<!-- Sem Itens -->
          			<?php 
          				if( !isset ( $_SESSION['_app_cart_'.$_SESSION['_app_user'] ['id'] ] ) || count ( $_SESSION['_app_cart_'.$_SESSION['_app_user'] ['id'] ] )  == 0 )
          				{  	
          			?>
          			<div class="row-fluid">
						<div class="alert alert-info">
          				<h4>
          					<stron>Seu carrinho está vazio!</stron>
          				</h4>
          				<p>
          					Para adicionar produtos ao carrinho, procure pelo produto em nosso site e clique no botão "Comprar".
          					<br>
          					<a href="?ctrl=index"> <strong> Voltar para a Loja </strong> </a> 
          				</p>
          			</div>
      				</div><!--/row-->	
          			<!-- Sem Itens -->
          			<?php
						}
						else
						{ 
          			?> 
          			<!-- Itens -->
          			<table class="table table-bordered">
    			 		<thead>
    			 			<tr>
								<th>Produto</th>
								<th style="text-align: center">Peças</th>
								<th style="text-align: center">Preço</th>
								<th style="text-align: center">Valor Total</th>
								<th></th>
								
							</tr>
						</thead>
						<tbody>
    						<?php 
    						    $num_total     = 0;
								$num_qtd_pecas = 0;
								
    							foreach( $v_carrinho AS $o_carrinho )
								{
									$num_total     = $num_total     + $o_carrinho->getValorTotal();  
									$num_qtd_pecas = $num_qtd_pecas + $o_carrinho->getQtdTotal();  
							?>
									<tr>
    									<td style="width: 60%" >
											<div class="media">
    											<a class="pull-left" href="?ctrl=produto&action=detalhar&id_prod=<?php echo $o_carrinho->getIdProd(); ?>">
    												<img style="width: 70px; height: 70px"  class="media-object" src="<?php echo $o_carrinho->getImagemProd(); ?>">
    											</a>
    											<div class="media-body">
    												<h4 class="media-heading"><?php echo $o_carrinho->getDescricaoProd(); ?> </h4>
    												<?php echo 'ref.: '.$o_carrinho->getReferenciaProd() ?>
    											</div>
    										</div> 	
    									</td>
    							<td style="width: 7%; text-align: center"> <?php  echo $o_carrinho->getQtdTotal(); ?></td>
    							<td style="width: 10%; text-align: center"><?php  echo 'R$ '.number_format($o_carrinho->getPrecoProd(), 2, ',', '.'); ?> </td>
    							<td style="width: 13%; text-align: center"><?php  echo 'R$ '.number_format($o_carrinho->getValorTotal(), 2, ',', '.'); ?></td>
    							<td style="width: 10%" >
    								<a href="?ctrl=pedido&action=addcart&edit=true&id_prod=<?php echo $o_carrinho->getIdProd(); ?>" class="btn-block btn btn-info">editar</a>
    							 	<a href="?ctrl=pedido&action=delitemcart&id_prod=<?php echo $o_carrinho->getIdProd(); ?>" class="btn-block btn btn-danger">excluir</a>
    							</td>
    						</tr>
    						
    						<?php
								}
							?>  						
						</tbody>
    				</table>
    				<table class="table table-bordered" >
    					<tbody>
    						<tr>
    							<td style="width: 60%" ><strong> Totais </strong></td>
    							<td style="width: 7%; text-align: center"" ><strong> <?php echo $num_qtd_pecas; ?></strong></td>
    							<td style="width: 10%" ></td>
    						   	<td style="width: 13%; text-align: center"><strong> <?php echo 'R$ '.number_format($num_total, 2, ',', '.');?></strong></td>
    						   	<td style="width: 10%" ></td>
    						</tr>
    					</tbody>
    				</table>
    				<!-- Fim - Itens -->
    				
    				<div class="row-fluid">
    					<div class="span5 offset1">
    						<a href="?ctrl=index" class="btn btn-block btn-large">comprar mais produtos</a>
    					</div>
    					<div class="span5">
    						<a href="?ctrl=pedido&action=endcart" class="btn btn-block btn-large btn-success">concluir compra</a>
    					</div>
   					</div>
    			<?php	
    			 }  // Fim com Itens
    			?>	
       			</div> <!--Span-->
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>

   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
  	</body>
</html>