<?php
 	$v_params 	   = $this->getParams();
	$o_cliente     = $v_params['o_cliente'];
	
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
    	<!-- Menus -->
    	<?php
    		if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
			{	
    	 ?>
    	 <!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li class="active" ><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li class="active"><a href="?ctrl=cliente&action=list">Clientes</a></li>
              				<li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
    	
    	 <?php 
			}
			else
    	 	{	
    	 ?>
    	 <!-- Menu Cliente-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Meu Carrinho </a> </li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li class="active"><a href="?ctrl=cliente&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=pedido&action=list">Meus Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Meus Títulos</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
   	 	<?php
   	 		}
   	 	?> 
   	 	<!-- Fim Menus-->	
    	<div class="container">
    		<div class="row-fluid">
    			<div class="span">
    				<div class="masthead">
        				<h3 class="muted">Cadastro</h3>
      				</div>
      				<hr>		
      				<form method="post" >
          				<div class="control-group">
              				<label class="control-label" for="cnpj_cpf"><i class=" "></i>CNPJ / CPF</label>
             	 			<div class="controls controls-row">
                				<input disabled="true" value="<?php echo $o_cliente->getCNPJ_CPF(); ?>" class="input-xxlarge" id="cnpj_cpf" name="cnpj_cpf" placeholder=" " type="text">
              				</div>
            			</div>
            			
          				<div class="control-group">
              				<label class="control-label" for="nomefantasia"><i class=" "></i>Nome Fantasia</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getNomeFantasia(); ?>" class="input-xxlarge" id="nomefantasia" name="nomefantasia" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="razaosocial"><i class=" "></i>Razão Social</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getRazaoSocial(); ?>" class="input-xxlarge" id="razaosocial" name="razaosocial" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="contato"><i class=" "></i>Contato</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getContato(); ?>" class="input-xxlarge" id="contato" name="contato" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="email"><i class=" "></i>E-mail</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getEmail(); ?>" class="input-xxlarge" id="email" name="email" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="inscricao"><i class=" "></i>Inscrição</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getInscricao(); ?>" class="input-xxlarge" id="inscricao" name="inscricao" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="fone"><i class=" "></i>Telefone</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getFone(); ?>" class="input-xxlarge" id="fone" name="fone" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="logradouro"><i class=" "></i>Logradouro</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getLogradouro(); ?>" class="input-xxlarge" id="logradouro" name="logradouro" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="numero"><i class=" "></i>Número</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getNumero(); ?>" class="input-xxlarge" id="numero" name="numero" placeholder=" " type="text">
              				</div>
            			</div>
			
						<div class="control-group">
              				<label class="control-label" for="complemento"><i class=" "></i>Complemento</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getComplemento(); ?>" class="input-xxlarge" id="complemento" name="complemento" placeholder=" " type="text">
              				</div>
            			</div>
			
						<div class="control-group">
              				<label class="control-label" for="bairro"><i class=" "></i>Bairro</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getBairro(); ?>" class="input-xxlarge" id="bairro" name="bairro" placeholder=" " type="text">
              				</div>
            			</div>
			
						<div class="control-group">
              				<label class="control-label" for="cidade"><i class=" "></i>Cidade</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getCidade(); ?>" class="input-xxlarge" id="cidade" name="cidade" placeholder=" " type="text">
              				</div>
            			</div>	
			
						<div class="control-group">
              				<label class="control-label" for="cep"><i class=" "></i>CEP</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getCep(); ?>" class="input-xxlarge" id="cep" name="cep" placeholder=" " type="text">
              				</div>
            			</div>
			
						<div class="control-group">
              				<label class="control-label" for="uf"><i class=" "></i>UF</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getUF(); ?>" class="input-xxlarge" id="uf" name="uf" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="e_logradouro"><i class=" "></i>Entrega - Logradouro</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getEntregaLogradouro(); ?>" class="input-xxlarge" id="e_logradouro" name="e_logradouro" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="e_numero"><i class=" "></i>Entrega - Número</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getEntregaNumero(); ?>" class="input-xxlarge" id="e_numero" name="e_numero" placeholder=" " type="text">
              				</div>
            			</div>
			
						<div class="control-group">
              				<label class="control-label" for="e_complemento"><i class=" "></i>Entrega - Complemento</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getEntregaComplemento(); ?>" class="input-xxlarge" id="e_complemento" name="e_complemento" placeholder=" " type="text">
              				</div>
            			</div>
			
						<div class="control-group">
              				<label class="control-label" for="e_bairro"><i class=""></i>Entrega - Bairro</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getEntregaBairro(); ?>" class="input-xxlarge" id="e_bairro" name="e_bairro" placeholder=" " type="text">
              				</div>
            			</div>
			
						<div class="control-group">
              				<label class="control-label" for="e_cidade"><i class=" "></i>Entrega - Cidade</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getEntregaCidade(); ?>" class="input-xxlarge" id="e_cidade" name="e_cidade" placeholder="" type="text">
              				</div>
            			</div>	
			
						<div class="control-group">
              				<label class="control-label" for="e_cep"><i class=" "></i>Entrega - CEP</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_cliente->getEntregaCep(); ?>" class="input-xxlarge" id="e_cep" name="e_cep" placeholder=" " type="text">
              				</div>
            			</div>
			
            			<div class="control-group">
    						<div class="controls">
    							<?php
    								if( $_SESSION['_app_user']['tppessoa'] != 'vendedor' )
									{	
    	 						?>
    									<a href="?ctrl=index" class="btn btn-danger">cancelar</a>
    							<?php 
									}
									else
									{
    							?>
    									<a href="?ctrl=cliente&action=list" class="btn btn-danger">cancelar</a>
    							<?php
									}
    							?>	
      							<button type="submit" class="btn btn-success">salvar</button>
      							<?php
    								if( $_SESSION['_app_user']['tppessoa'] != 'vendedor' )
									{	
    	 						?>
      							<a href="?ctrl=cliente&action=altsenha" class="btn btn-info">alterar senha</a>
      							<?php
									}
      							?>
   							</div>
   						</div>
					</form>

          			
       			</div> <!--Span-->
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>

   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
  	</body>
</html>