<?php
	$v_params 	= $this->getParams();
	$o_pedido  = $v_params['o_pedido']; 
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
    	  <!-- Menus -->
    	<?php
    		if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
			{	
    	 ?>
    	 <!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=cliente&action=list">Clientes</a></li>
              				<li class="active"><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
    	
    	 <?php 
			}
			else
    	 	{	
    	 ?>
    	 <!-- Menu Cliente-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Meu Carrinho </a> </li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=cliente&action=edit">Cadastro</a></li>
              				<li class="active"><a href="?ctrl=pedido&action=list">Meus Pedidos</a></li>
              				<li> <a href="?ctrl=titulo&action=list">Meus Títulos</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
   	 	<?php
   	 		}
   	 	?> 
   	 	<!-- Fim Menus-->
 		<div class="container">
    		<div class="row-fluid">
    			<!--<ul class="breadcrumb">
				<li><a href="#">Meus Pedidos</a> <span class="divider">/</span></li>
				  <li class="active">Pedido</li>
				</ul> -->
				<div class="masthead">
        		   <h3 class="muted">Pedido</h3>
      			</div>
      			<hr>
    			<p style="font-size: 18px"><strong>Data:</strong> <?php echo strftime("%d/%m/%Y", strtotime($o_pedido->getData())); ?> </p> 
    			<?php 
    				if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
					{
				?>
					<p style="font-size: 18px"><strong>CNPJ / CPF:</strong> <?php echo $o_pedido->getCNPJ_CPFCli(); ?> </p>
					<p style="font-size: 18px"><strong>Razão Social:</strong> <?php echo$o_pedido->getRazaoSocialCli(); ?> </p>
					
				<?php
					}
				?>
    			<p style="font-size: 18px"> <strong>Condição de Pagamento: </strong> <?php echo $o_pedido->getCondPagStr(); ?> </p>
   				<?php 
   					if( trim($o_pedido->getObs()) <> '' )
					{
   				?>
   				<p style="font-size: 18px"><strong>Observações: </strong> <?php echo $o_pedido->getObs(); ?> </p>
   				<?php 
   					} 	
   				?>
   				<br>
   				 
    		<!-- Itens / Grades -->
    		<?php 
    			$boo_muda   = true;
				$int_linha  = 0; 
				$boo_cor    = false;
				$num_valtot = 0;
				$int_qtdtot = 0;
    		?>
    		<div class="bs-docs-example">
    			<table class="table table-bordered">
    				<thead>
    					 <tr>
                  			<th>Produto</th>
                  			<th style="text-align: center">Grade</th>
                  			<th style="text-align: center">Quantidade</th>
                  			<th style="text-align: center">Preço</th>
                  			<th style="text-align: center">Total</th>
                		</tr>
              		</thead>
              		<tbody>
    						<?php 
    							foreach( $o_pedido->getItens() AS $o_pedidoitem )
								{
							?>		
									<tr <?php if( $boo_cor ){ ?> class="warning" <?php } ?> >
										<?php
											if ( $boo_muda ) 
											{ 
										?>
 	                				 		<td rowspan="<?php echo $o_pedidoitem->getQtdGrades(); ?>" <?php if( $boo_cor ){ ?> class="warning" <?php } ?> style="width: 60%">
 	                				 			<strong>
 	                				 				<?php echo $o_pedidoitem->getProdutoStr(); ?>
 	                				 			</strong>
 	                				 		</td>
                 				 	    <?php // fim if 
											}
											
											$int_linha += 1;
											
											if ( $int_linha == $o_pedidoitem->getQtdGrades() )
											{
											    $boo_muda  = true;
												$boo_cor   = !$boo_cor; 
												$int_linha = 0;
											}
											else
											{
											 	$boo_muda  = false;
											}
											$num_totgrade = $o_pedidoitem->getPreco() * $o_pedidoitem->getQuantidade();
											$num_valtot  += $num_totgrade;
											$int_qtdtot  += $o_pedidoitem->getQuantidade();	 
                 				 	    ?>
                 				 	    <td style="text-align: center; width: 7%"><?php echo $o_pedidoitem->getGrade(); ?></td>
                   						<td style="text-align: center; width: 7%"> <?php echo $o_pedidoitem->getQuantidade(); ?></td>
                  						<td style="text-align: center; width: 12%"> <?php  echo 'R$ '.number_format( $o_pedidoitem->getPreco(), 2, ',', '.'); ?></td>
                  						<td style="text-align: center; width: 14%"> <?php  echo 'R$ '.number_format( $num_totgrade, 2, ',', '.'); ?></td>
                					</tr>
									
    						<?php
								}
    						?>
    
              		</tbody>
						<!-- Totais -->
						<td> <strong> Totais </strong> </td>
						<td></td>
                   		<td style="text-align: center"> <strong><?php echo $int_qtdtot; ?></strong></td>
                   		<td></td>
                  		<td style="text-align: center"> <strong><?php  echo 'R$ '.number_format( $num_valtot, 2, ',', '.'); ?></strong></td>
						              		
            	</table>
         	</div>
         	<br>
         	<p style="">
         	<span class="label label-important">	
         	Obrigado por escolher Amora Morena Jeans, todos pedidos estão sujeitos a analise financeira e consulta de disponibilidade em estoque.
         	</span>
         	</p>
         	<hr>
    		<div class="row-fluid">
    			<div class="span5 offset1">
    			   <a href="?ctrl=pedido&action=list" class="btn btn-block btn-large">voltar</a>
    			</div>
    			<div class="span5">
    				<a href="?ctrl=pedido&action=send&id_ped="<?php echo $o_pedido->getId(); ?> class="btn btn-block btn-large btn-info">reenviar e-mail</a>
    			</div>
   			</div>
    			
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>
      		
   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
  	</body>
</html>

