<?php
$v_params = $this->getParams();
$v_mensagens = $v_params['v_mensagens'];
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>SeragiWeb</title>

        <!-- Le styles -->
        <link href="view/css/bootstrap.css" rel="stylesheet">

        <style type="text/css">
            body {
                padding-top: 	60px;
                padding-bottom: 40px;
            }
            .sidebar-nav {
                padding: 9px 0;
            }

            @media (max-width: 980px) {
                /* Enable use of floated navbar text */
                .navbar-text.pull-right {
                    float: none;
                    padding-left:  5px;
                    padding-right: 5px;
                }
            }

            #item img {
                height: 200px;
                width : 200px; 
            }
        </style>

        <link href="view/css/bootstrap-responsive.css" rel="stylesheet">
    </head>
    <body>  	
        <!-- Menus -->
        <?php
        if ($_SESSION['_app_user']['tppessoa'] == 'vendedor') {
            ?>
            <!-- Menu Vendedor-->
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="brand" href="#">SeragiWeb</a>
                        <div class="nav-collapse collapse">
                            <ul class="nav pull-right">
                                <li><a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho Itens:123 R$ 9999,00 </a></li>  
                                <li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
                            </ul>

                            <ul class="nav">
                                <li class="active" ><a href="?ctrl=index">Home</a></li>
                                <li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
                                <li><a href="?ctrl=cliente&action=list">Clientes</a></li>
                                <li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
                                <li><a href="?ctrl=titulo&action=list">Títulos</a></li>
                                <li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
                            </ul>

                            <form class="navbar-search pull-left" method="get">
                                <input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
                            </form>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!-- Fim Menu-->

            <?php
        } else {
            ?>
            <!-- Menu Cliente-->
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="brand" href="#">SeragiWeb</a>
                        <div class="nav-collapse collapse">
                            <ul class="nav pull-right">
                                <li> <a href="?ctrl=pedido&action=showcart">Itens: 77 R$ 9999,00 <i class="icon-shopping-cart icon-white"></i> Meu Carrinho  </a> </li>  
                                <li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
                            </ul>

                            <ul class="nav">
                                <li class="active"><a href="?ctrl=index">Home</a></li>
                                <li><a href="?ctrl=cliente&action=edit">Cadastro</a></li>
                                <li><a href="?ctrl=pedido&action=list">Meus Pedidos</a></li>
                                <li><a href="?ctrl=titulo&action=list">Meus Títulos</a></li>
                            </ul>

                            <form class="navbar-search pull-left" method="get">
                                <input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
                            </form>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!-- Fim Menu-->
    <?php
}
?>
        <div class="container" style="text-align: right">
            <div class="row-fluid">
                <div id="menu-0">
                    <ul>
                        <li><a href="#">Jeans Feminino</a></li> 
                        <li><a href="#">Jeans Masculino</a></li>
                        <li class="novoProduto "><a href="#" class="link_limpo">Novos Produtos</a></li>
                    </ul>
                </div>
                <div class="span">	
                    <span class="label">Bem Vindo(a), &nbsp; <?php echo $_SESSION['_app_user']['razaosocial']; ?> </span>
                </div>
            </div>
        </div>


        <!-- Fim Menus-->   	 	
        <div class="container">
            <div class="row-fluid">
                <!-- Barra Lateral -->
                <div id="sidebar" class="span3">
                    <div class="well sidebar-nav">
                        <ul class="nav nav-list">
                            <li class="nav-header">Jeans</li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=1"><strong> Masculino </strong></a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=11"> &nbsp;&nbsp;&nbsp; Bermuda</a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=12"> &nbsp;&nbsp;&nbsp; Calça</a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=2"><strong>Feminino</strong></a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=21"> &nbsp;&nbsp;&nbsp; Calça</a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=22"> &nbsp;&nbsp;&nbsp; Cigarrete</a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=23"> &nbsp;&nbsp;&nbsp; Shorts</a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=24"> &nbsp;&nbsp;&nbsp; Slin</a></li>
                            <li> <a href="?ctrl=produto&action=listarProdutos&in_tpser=3"><strong>Infantil</strong></a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=4"><strong>Promoção</strong></a></li>
                            <li><a href="?ctrl=produto&action=listarProdutos&in_tpser=5"><strong>Saldo</strong></a></li>
                        </ul>
                    </div>

                    <!--
                    <div class="well">
                                    <strong>Razão Social: </strong><?php echo $_SESSION['_app_user']['razaosocial']; ?>
                            </div>
                    -->

                </div>
                <!--Fim Barra Lateral -->
                <div class="span9">

<?php
if ($_SESSION['_app_user']['tppessoa'] == 'vendedor') {
    if (count($v_mensagens) == 0) {
        ?>	
                            <div class="row-fluid">
                                <div class="alert alert-info">
                                    <h4>
                                        <stron>Sem Mensagens!</stron>
                                    </h4>
                                    <p>
                                        Nenhuma mensagem em aberto no período.
                                    </p>
                                </div>
                            </div><!--/row-->	
                            <!-- Sem Mensagens -->
        <?php
    } else {
        ?> 
                            <!-- Menagens -->
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Data Inicial</th>
                                        <th>Data Final  </th>
                                        <th>Mensagem    </th>
                                        <th>Marcar Como</th>
                                    </tr>
                                </thead>
                                <tbody>
        <?php
        foreach ($v_mensagens AS $o_mensagem) {
            if ($o_mensagem->getConfLeitura() == 'f') {
                $boo_lida = 'true';
            } else {
                $boo_lida = 'false';
            }
            ?>
                                        <tr>
                                            <td style="width: 10%"> <?php echo strftime("%d/%m/%Y", strtotime($o_mensagem->getDataIni())); ?></td>
                                            <td style="width: 10%"> <?php echo strftime("%d/%m/%Y", strtotime($o_mensagem->getDataFim())); ?></td>
                                            <td style="width: 50%"> <?php echo $o_mensagem->getMensagem() ?></td>
                                            <td style="width: 15%">
                                                <a href="?ctrl=mensagem&action=read&idx=true&id_men=<?php echo $o_mensagem->getId() . '&b_l=' . $boo_lida; ?>" class="btn-block btn <?php if ($boo_lida == 'true') {
                                echo 'btn-success';
                            } else {
                                echo 'btn-danger';
                            } ?>">
                                        <?php if ($boo_lida == 'true') {
                                            echo 'lida';
                                        } else {
                                            echo 'não lida';
                                        } ?>
                                                </a>
                                            </td>
                                        </tr>	
            <?php
        } // foreach
    }
    ?>  						
                            </tbody>
                        </table>

    <?php
} else {
    ?>
                            <div id="home">
                               <div id="homec1">
                                   <img src="view/img/home_banner.png" alt="">
                               </div> 
                               <div id="homec2">
                                   <img src="view/img/home_feminino.jpg" alt="">
                                   <img src="view/img/home_masculino.jpg" alt="">
                               </div> 
                            </div>
                            
                            
                            
                            
<!--                        <div class="carousel" >
                            <div id="myCarousel" class="carousel slide">
                                <ol class="carousel-indicators">
                                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                    <li data-target="#myCarousel" data-slide-to="1"></li>
                                    <li data-target="#myCarousel" data-slide-to="2"></li>
                                </ol>
                                 Carousel items 
                                <div class="carousel-inner">
                                    <div class="active item">
                                        <img src="view/img/colecao/foto_5.jpg" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="view/img/colecao/foto_2_002.jpg" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="view/img/colecao/foto_4_002.jpg" alt="">
                                    </div>
                                </div>
                                 Carousel nav 
                                <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                                <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a> 
                            </div>
                        </div>-->
    <?php
}
?>

                </div><!--/span-->
            </div><!--/row-->
            <div class="row-fluid">
                <div class="centralizada"><img src="view/img/ArquivoExibir.png" alt="Promoções"></div>
                
                <div id="lancamentos">
                    <ul>
                        <li>
                            <img src="view/img/home_feminino.jpg" alt="">
                         <h5>Calça jeans feminina skinny – 230234 – Grade com 11 peças
</h5>    
                         <p>R$ 511,50</p>
                         <span ><a class="btn_mais_detalhes" href="#">Mais Detalhes +</a></span>
                        </li>
                    </ul>
                        
                </div>
                <div class="centralizada"><img src="view/img/ArquivoExibir.png" alt="Promoções"></div>            
            </div>
            <hr>
            <footer> 
                &copy;2013 - Agape World Inform&aacute;tica Ltda - 
                <a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
            </footer>
        </div><!--/.fluid-container-->	
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="view/js/bootstrap.min.js"></script>
    </body>
</html>