<?php
 	$v_params 	 	  = $this->getParams();
	$v_titulos        = $v_params['v_titulos']; 
	$qtd_titulos 	  = $v_params['qtd_titulos'];
	$dat_dataini      = $v_params['dat_dataini'];
	$dat_datafim      = $v_params['dat_datafim'];
	$int_pagina	   	  = $v_params['int_pagina']; 
	$int_numporpagina = $v_params['int_numporpagina'];
	$int_totalreg 	  = $v_params['int_totalreg'];
	$v_clientes   	  = $v_params['v_clientes'];
	$int_idcliente    = $v_params['int_idcliente']; 		
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
		<link href="view/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
		<link href="view/css/bootstrap-combined.min.css" rel="stylesheet">
	 
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
    	  <!-- Menus -->
    	<?php
    		if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
			{	
    	 ?>
    	 <!-- Menu Vendedor-->
    	 <!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li ><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=cliente&action=list">Clientes</a></li>
              				<li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li  class="active"><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
    	
    	 <?php 
			}
			else
    	 	{	
    	 ?>
    	 <!-- Menu Cliente-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Meu Carrinho </a> </li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=cliente&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=pedido&action=list">Meus Pedidos</a></li>
              				<li  class="active"><a href="?ctrl=titulo&action=list">Meus Títulos</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
   	 	<?php
   	 		}
   	 	?> 
   	 	<!-- Fim Menus-->
 		<div class="container">
    		<div class="row-fluid">
    			<div class="span">
    				<form method="post" >
					<div class="well well-small" style="text-align: center">
 						
 						Vencimento de &nbsp
 						<div id="dataini" class="input-append date">
      						<input value="<?php echo $dat_dataini; ?>" type="text" class="input-small" name="dataini"></input>
     			 			 <span class="add-on">
        					 	<i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      						</span>
    					</div>
    					&nbsp até &nbsp
    					<div id="datafim" class="input-append date">
      						<input value="<?php echo $dat_datafim; ?>" type="text" class="input-small" name="datafim" ></input>
     			 			 <span class="add-on">
        					 	<i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      						</span>
    					</div>
    					<!-- Clientes --> 
    					<?php
    						if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
							{	
    	 				?>
    	 				&nbsp
    					<div id="cliente" class="input-append">
    					<select class="input-xxlarge" name="cliente" id="cliente" >
    						<option value="-1"> Todos Clientes </option>
						<?php
							foreach( $v_clientes AS $o_cliente )
							{
					    ?>	
								<option <?php if( $o_cliente->getId() == $int_idcliente ){ ?> selected="" <?php } ?> value="<?php echo $o_cliente->getId(); ?>"> <?php echo $o_cliente->getCNPJ_CPF() . ' - '. $o_cliente->getRazaoSocial() ; ?> </option>
						<?php
							} 
						?>
						</select>
						</div>
						<?php
							}
    	 				?>
    					<!-- Fim - CLiente -->
    					
    					&nbsp
    					<div id="" class="input-append">
    						<button type="submit" class="btn"> filtrar </button>
    					</div>
					</div>
					</form>
					      				
          			<!-- Sem Titulos -->
          			<?php 
          				if( $qtd_titulos == 0 )
          				{  	
          			?>
          			<div class="row-fluid">
						<div class="alert alert-info">
          				<h4>
          					<stron>Sem Títulos Vencendo no Período!</stron>
          				</h4>
          				<p>
          					Nenhum título foi localizado com a data de vencimento no período!
          				</p>
          			</div>
      				</div><!--/row-->	
          			<!-- Sem Itens -->
          			<?php
						}
						else
						{ 
          			?> 
          			<!-- Itens -->
          			<table class="table table-bordered">
    			 		<thead>
    			 			<tr>
								<?php
    							if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
								{	
    	 						?>
								<th>Cliente </th>
								<?php
								}
								?>
								<th>Emissão </th>
								<th>Vencimento</th>
								<th>Recebimento</th>
								<th>Documento</th>
								<th>Valor</th>
							</tr>
						</thead>
						<tbody>
    						<?php
    							foreach( $v_titulos AS $o_titulo )
								{		  
							?>
									<tr>
    									<?php
    									if( $_SESSION['_app_user']['tppessoa'] == 'vendedor' )
										{	
    	 								?>
    	 								<td style="width: 40%"> <?php  echo $o_titulo->getRazaoSocialCli(); ?></td>
										<td style="width: 10%"> <?php  echo strftime("%d/%m/%Y", strtotime($o_titulo->getDtEmissao())); ?></td>
    									<td style="width: 10%"> <?php  echo strftime("%d/%m/%Y", strtotime($o_titulo->getDtVencimento())); ?></td>
    									<td style="width: 10%"> <?php if( $o_titulo->getDtRecebimento() <> '' ) echo strftime("%d/%m/%Y", strtotime($o_titulo->getDtRecebimento())); ?></td>
    									<td> <?php  echo $o_titulo->getDocumento(); ?></td>
    									<td> <?php  echo 'R$ '.number_format( $o_titulo->getValor(), 2, ',', '.'); ?></td>
										<?php
										}
										else
										{
										?>
    									<td style="width: 15%"> <?php  echo strftime("%d/%m/%Y", strtotime($o_titulo->getDtEmissao())); ?></td>
    									<td style="width: 15%"> <?php  echo strftime("%d/%m/%Y", strtotime($o_titulo->getDtVencimento())); ?></td>
    									<td style="width: 15%"> <?php if( $o_titulo->getDtRecebimento() <> '' ) echo strftime("%d/%m/%Y", strtotime($o_titulo->getDtRecebimento())); ?></td>
    									<td> <?php  echo $o_titulo->getDocumento(); ?></td>
    									<td> <?php  echo 'R$ '.number_format( $o_titulo->getValor(), 2, ',', '.'); ?></td>
    									<?php
										}
										?>
    								</tr>
    						<?php
								}
							?>  						
						</tbody>
    				</table>
    				
    				<!-- Paginação -->
    			    <ul class="pager">
    			    <?php
    			    	$int_prox   = $int_pagina + 1;
						$int_ant    = $int_pagina - 1;		
						$int_ultima = @ceil( $int_totalreg / $int_numporpagina );
					
    			       if ( $int_ant >= 0 )
					   {
					 ?>
					 	<li class="previous">
					 	<a href="?ctrl=titulo&action=list&in_pg=<?php echo $int_ant.'&dt_i='.$dat_dataini.'&dt_f='.$dat_datafim.'&id_cli='.$int_idcliente; ?>">&larr; Títulos anteriores</a>
					 <?php
					   }
					   else
					   {
					 ?> 
						<li class="previous disabled">
						<a href="">&larr; Títulos anteriores</a>	
					 <?php
					   }
					 ?>		
    					</li>
    				
    				<?php					
    			       if ( $int_prox < $int_ultima )
					   {
					 ?>
					 	<li class="next">
					 	<a href="?ctrl=titulo&action=list&in_pg=<?php echo $int_prox.'&dt_i='.$dat_dataini.'&dt_f='.$dat_datafim.'&id_cli='.$int_idcliente; ?>">Mais títulos &rarr;</a>
					 <?php
					   }
					   else
					   {
					 ?> 
						<li class="next disabled">
						<a href="">Mais títulos &rarr;</a>	
					 <?php
					   }
					 ?>		
    					</li>
    				</ul>
    				<!-- Fim paginação -->
    			<?php	
    			 }  // Fim com Itens
    			?>	
       			</div> <!--Span-->
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>

   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
		<script src="view/js/bootstrap-datetimepicker.min.js"></script>	
		<script src="view/js/bootstrap-datetimepicker.pt-BR.js"></script>
    	<script type="text/javascript">
      		$('#dataini').datetimepicker({
        		format: 'dd/MM/yyyy',
        		language: 'pt-BR',
        		pickTime: false
      		});
      		$('#datafim').datetimepicker({
        		format: 'dd/MM/yyyy',
        		language: 'pt-BR',
        		pickTime: false
      		});
    	</script>	
  	</body>
</html>