<?php
 	$v_params 	      = $this->getParams();
	$v_clientes       = $v_params['v_clientes']; 
	$qtd_clientes     = $v_params['qtd_clientes'];
	$str_busca 	      = $v_params['str_busca'];
	$int_pagina	   	  = $v_params['int_pagina']; 
	$int_numporpagina = $v_params['int_numporpagina'];
	$int_totalreg 	  = $v_params['int_totalreg']; 		
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
		<link href="view/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
		<link href="view/css/bootstrap-combined.min.css" rel="stylesheet">
	 
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
    	<!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li class="active" ><a href="?ctrl=cliente&action=list">Clientes</a></li>
              				<li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->
 		<div class="container">
    		<div class="row-fluid">
    			<div class="span">
    				<form method="post" >
					<div class="well well-small" style="text-align: center">
 						<div id="dataini" class="input-append">
      						<input value="<?php echo $str_busca; ?>" type="text" class="input-large" name="str_busca"></input>
    					</div>
    					&nbsp
    					<div id="" class="input-append">
    						<button type="submit" class="btn"> filtrar </button>
    					</div>
					</div>
					</form>
					      				
          			<!-- Sem Clientes -->
          			<?php 
          				if( $qtd_clientes == 0 )
          				{  	
          			?>
          			<div class="row-fluid">
						<div class="alert alert-info">
          				<h4>
          					<stron>Sem Clientes!</stron>
          				</h4>
          				<p>
          					Nenhum cliente foi encontrado com os filtros!
          				</p>
          			</div>
      				</div><!--/row-->	
          			<!-- Sem Clientes -->
          			<?php
						}
						else
						{ 
          			?> 
          			<!--Clientes -->
          			<table class="table table-bordered">
    			 		<thead>
    			 			<tr>
								<th>CNPJ / CPF</th>
								<th>Razão Social</th>
								<th>Telefone</th>
								<th>E-mail</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							 
    						<?php    						
    							foreach( $v_clientes AS $o_cliente )
								{		  
							?>
									<tr>
    									<td style="width: 13%"> <?php echo $o_cliente->getCNPJ_CPF(); ?></td>
    									<td style="width: 44%"> <?php echo $o_cliente->getRazaoSocial(); ?></td>
    									<td style="width: 13%"> <?php echo $o_cliente->getFone(); ?></td>
    									<td style="width: 20%"> <?php echo $o_cliente->getEmail(); ?></td>
    									<td>
    										<a href="?ctrl=cliente&action=edit&id_cli=<?php echo $o_cliente->getId(); ?>" class="btn-block btn btn-info">editar</a>
    									</td>
    								</tr>
    						
    						<?php
								}
							?>  						
						</tbody>
    				</table>
    				
    				<!-- Paginação -->
    			    <ul class="pager">
    			    <?php
    			    	$int_prox   = $int_pagina + 1;
						$int_ant    = $int_pagina - 1;		
						$int_ultima = @ceil( $int_totalreg / $int_numporpagina );
					
    			       if ( $int_ant >= 0 )
					   {
					 ?>
					 	<li class="previous">
					 	<a href="?ctrl=cliente&action=list&in_pg=<?php echo $int_ant.'&st_ser='.$str_busca; ?>">&larr; Clientes anteriores</a>
					 <?php
					   }
					   else
					   {
					 ?> 
						<li class="previous disabled">
						<a href="">&larr; Clientes anteriores</a>	
					 <?php
					   }
					 ?>		
    					</li>
    				
    				<?php					
    			       if ( $int_prox < $int_ultima )
					   {
					 ?>
					 	<li class="next">
					 	<a href="?ctrl=cliente&action=list&in_pg=<?php echo $int_prox.'&st_ser='.$str_busca; ?>">Mais clientes &rarr;</a>
					 <?php
					   }
					   else
					   {
					 ?> 
						<li class="next disabled">
						<a href="">Mais clientes &rarr;</a>	
					 <?php
					   }
					 ?>		
    					</li>
    				</ul>
    				<!-- Fim paginação -->
    			<?php	
    			 }  // Fim com Itens
    			?>	
       			</div> <!--Span-->
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>

   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
			
  	</body>
</html>