<?php
 	$v_params 	   = $this->getParams();
	$o_vendedor    = $v_params['o_vendedor'];
?>

<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>SeragiWeb</title>
    
    	<!-- Le styles -->
		<link href="view/css/bootstrap.css" rel="stylesheet">
    	<style type="text/css">
      		body {
        	   padding-top: 	60px;
        	   padding-bottom: 40px;
      		}
      		.sidebar-nav {
        	   padding: 9px 0;
      		}

      		@media (max-width: 980px) {
        		/* Enable use of floated navbar text */
        		.navbar-text.pull-right {
          			float: none;
          			padding-left:  5px;
          			padding-right: 5px;
        		}
      		}
      
      		#item img {
      			height: 200px;
        		width : 200px; 
      		}
    	</style>
    
    	<link href="view/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
    <body>
    	<!-- Menu Vendedor-->
    	<div class="navbar navbar-inverse navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container">
    				<a class="brand" href="#">SeragiWeb</a>
           			<div class="nav-collapse collapse">
            			<ul class="nav pull-right">
            				<li> <a href="?ctrl=pedido&action=showcart"> <i class="icon-shopping-cart icon-white"></i> Carrinho</a></li>  
            				<li> <a href="?ctrl=section&action=logout">  <i class="icon-off icon-white"> </i> Sair </a> </li> 
           				</ul>
            
            			<ul class="nav">
             	 			<li><a href="?ctrl=index">Home</a></li>
              				<li class="active" ><a href="?ctrl=vendedor&action=edit">Cadastro</a></li>
              				<li><a href="?ctrl=pedido&action=list">Pedidos</a></li>
              				<li><a href="?ctrl=titulo&action=list">Títulos</a></li>
              				<li><a href="?ctrl=mensagem&action=list">Mensagens</a></li>
            			</ul>
            
            			<form class="navbar-search pull-left" method="get">
    	    				<input id="_busca_" name="_busca_" type="text" class="search-query" placeholder="Buscar">
    	   	 			</form>
          			</div><!--/.nav-collapse -->
        		</div>
      		</div>
    	</div>
   	 	<!-- Fim Menu-->	
    	<div class="container">
    		<div class="row-fluid">
    			<div class="span">
    				<div class="masthead">
        				<h3 class="muted">Cadastro</h3>
      				</div>
      				<hr>		
      				<form method="post" >
          				<div class="control-group">
              				<label class="control-label" for="cnpj_cpf"><i class=" "></i>CNPJ / CPF</label>
             	 			<div class="controls controls-row">
                				<input disabled="true" value="<?php echo $o_vendedor->getCNPJ_CPF(); ?>" class="input-xxlarge" id="cnpj_cpf" name="cnpj_cpf" placeholder=" " type="text">
              				</div>
            			</div>
            			
          				<div class="control-group">
              				<label class="control-label" for="razaosocial"><i class=" "></i>Razão Social</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_vendedor->getRazaoSocial(); ?>" class="input-xxlarge" id="razaosocial" name="razaosocial" placeholder=" " type="text">
              				</div>
            			</div>
            			            			
            			<div class="control-group">
              				<label class="control-label" for="email"><i class=" "></i>E-mail</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_vendedor->getEmail(); ?>" class="input-xxlarge" id="email" name="email" placeholder=" " type="text">
              				</div>
            			</div>
            			
            			<div class="control-group">
              				<label class="control-label" for="fone"><i class=" "></i>Telefone</label>
             	 			<div class="controls controls-row">
                				<input value="<?php echo $o_vendedor->getFone(); ?>" class="input-xxlarge" id="fone" name="fone" placeholder=" " type="text">
              				</div>
            			</div>
            			
						<div class="control-group">
    						<div class="controls">
    							<a href="?ctrl=index" class="btn btn-danger">cancelar</a>
      							<button type="submit" class="btn btn-success">salvar</button>
      							<a href="?ctrl=vendedor&action=altsenha" class="btn btn-info">alterar senha</a>
   							</div>
   						</div>
					</form>          			
       			</div> <!--Span-->
      		</div><!--/row-->
			<hr>
      		<footer> 
      			&copy;2013 - Agape World Inform&aacute;tica Ltda - 
      			<a href=" http://www.agapeworld.com.br" >www.agapeworld.com.br</a> - Fone: (43) 3033-5886 – (43) 9914-9896 - E-mail: agape@agapeworld.com.br     		
      		</footer>

   		</div><!--/.fluid-container-->	
    	<script src="http://code.jquery.com/jquery-latest.js"></script>
		<script src="view/js/bootstrap.min.js"></script>
  	</body>
</html>